ku_djangoo/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views

from tutorial.quickstart import views as serializer_views

from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView, 
    TokenRefreshView, 
    TokenVerifyView
)

from polls import api
from ku_djangoo import asgi

from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', serializer_views.UserViewSet)
router.register(r'groups', serializer_views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/verify/protected-data/', api.ProtectedDataView.as_view(), name='ProtectedDataView'),
    path('api/token/login/cookie/', api.CustomLoginTokenAccessView.as_view(), name='CustomLoginTokenAccessView'),
    path('api/token/access/', api.AccessJWToken.as_view()),
    path('api/token/csrf/', api.get_csrf_token),
    path('api/token/csrf/test/', api.get_csrf_token_test),
    
    path('api/signup/', api.signup, name='SignUpAPI'),

    path('api/token/logout/cookie/', api.CustomLogoutTokenView.as_view(), name='CustomLogoutTokenView'),    
    path('api/token/check-login/cookie/', api.CustomCheckLoginStateTokenView.as_view(), name='CustomCheckLoginTokenView'),        
    path('api/token/refresh/cookie/', api.CustomTokenRefreshView.as_view(), name='CustomTokenRefreshView'),
    path('api/token/test/login/cookie/', api.TestUserInfoAndCookie.as_view(), name='TestUserInfoAndCookie'),
    path('api/top-models/', api.model_list_user, name='model_list_user'),
    path('api/top-datasets/', api.dataset_list_user, name='dataset_list_user'),
    path('api/login/check/', api.user_login_check, name='user_login_check'),
    path('api/user/', api.user_profile, name='user_profile'),
    path('api/user/models/', api.user_models, name='user_models'),
    path('api/user/private/models/', api.user_private_models, name='user_private_models'),
    path('api/user/models/page/', api.user_and_public_models_pages, name='user_and_public_models_pages'),
    path('api/user/private/datasets/', api.user_private_datasets_api, name='user_private_datasets'),
    path('api/user/datasets/', api.user_datasets_api, name='user_datasets'),
    path('api/user/datasets/page/', api.user_and_public_datasets_pages, name='user_and_public_datasets_pages'),
    path('api/test/', api.test_api, name='test_api'),    
    path('api/model/search/', api.search_model_by_name, name='search_model_by_name'),    
    path('api/model/upload/', api.model_form_post),
    path('api/dataset/upload/', api.dataset_form_post),
    path('api/dataset/fork/', api.fork_dataset_api),
    path('api/model/fork/', api.fork_model_api),
    path('api/model-dataset/relate/', api.relate_a_model_dataset),
    path('api/dataset/<int:id>/', api.DatasetDetail.as_view()),
    path('api/dataset/download/<int:id>/', api.download_dataset_zip),
    path('api/dataset/download/test/', api.test_download_dataset_zip),
    path('api/datasets/page/test/', api.test_page_range),
    path('api/datasets/page/', api.datasets_page_range),
    path('api/models/page/', api.models_page_range),
    path('api/model/download/<int:id>/', api.download_model_zip),
    path('api/model/<int:id>/', api.ModelDetail.as_view()),
    path('api/dataset/image/test-async-stream/', asgi.test_async_stream_view),
    path('api/dataset/image/test-async-file-stream/', asgi.test_async_file_streaming),
    path("api/dataset/blob/<int:user_id>/<str:dataset_name>/<path:image_path>/",
        api.get_dataset_image, name="get_dataset_image_api",
    ),
    path("api/model/blob/<int:user_id>/<str:model_name>/<path:image_path>/",
        api.get_model_image, name="get_model_image_api",
    ),
    path('api/dataset/blob/<int:user_id>/<str:dataset_name>/<path:path>/', 
        api.respond_dataset_file_tree, name="get dataset file"
    ),
    path('api/model/blob/<int:user_id>/<str:model_name>/<path:path>/', 
        api.respond_model_file_tree, name="get model file"
    ),
    path('api/dataset/tree/<int:user_id>/<str:dataset_name>/<path:path>/', 
        api.respond_dataset_file_tree, name="get dataset file tree"
    ),
    path('api/model/tree/<int:user_id>/<str:model_name>/<path:path>/', 
        api.respond_model_file_tree, name="get model file tree"
    ),
    path('api/dataset/tree/<int:user_id>/<str:dataset_name>/', 
        api.respond_dataset_file_tree, name="get dataset file tree"
    ),
    path('api/model/tree/<int:user_id>/<str:model_name>/', 
        api.respond_model_file_tree, name="get model file tree"
    ),
    re_path(r'api/dataset/.*\.csv$', api.get_csv_data, name='csv_view'), 
    path('api/dataset/save-minio/test/', api.save_dataset_file_to_minio_api),
    path('api/dataset/minio/<int:id>/', api.read_dataset_from_minio),
    path('api/dataset/minio/<int:id>/', api.delete_dataset_file_from_minio),
    path('api/dataset/minio/<int:id>/', api.update_dataset_file_in_minio),
    path('api/dataset/minio/test/', api.read_file_from_minio_test),
    path('api/dataset/get-minio/test/zip/', api.test_get_zip_file_from_minio),
    path('api/dataset/minio/test/list/', api.list_minio_bucket_object),
    path('api/dataset/minio/temp/', api.temp),
    path('api/task/', api.create_and_get_task_id),

    path('api/me/username/', api.get_request_username, name=''),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
    path("accounts/djangoo-login/", auth_views.LoginView.as_view(template_name="ku_djangoo/login_djangoo.html")),
    path("accounts/djangoo-profile/", auth_views.LoginView.as_view(template_name="ku_djangoo/login_djangoo.html")),
]

# if settings.DEBUG:

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[1])

# Above is for Development. For Production, for GET requests, serve static files by a web server like Nginx for better performance and security.

polls/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from . import api

app_name = 'polls'
urlpatterns = [
    path("", views.index_homepage_view, name="index"),
    path("search-dataset-name", views.search_dataset_name_view, name="search dataset name"),
    path("home/", views.index_homepage_view, name="index"),
    path("profile/", views.profile_view, name="profile"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("logout/", views.logout_view, name="logout"),
    path("login-view/", views.login_view, name="login view"),
    path("login-retry-view/", views.login_retry_view, name="login retry view"),
    path("login-view/login/", views.login_user, name="login"),
    path("login-retry-view/login/", views.login_user, name="retry login"),
    path("register-view/", views.register_view, name="register view"),
    path("register-retry-view/", views.register_retry_view, name="register retry view"),
    path("register-view/register/", views.register, name="register"),
    path("register-retry-view/register/", views.register, name="register retry "),
    path("upload-model/", views.upload_model, name="upload model form"),
    path("upload-folder/", views.upload_folder_view, name="upload folder view"),
    path("public-dataset-list-view/", views.public_dataset_list_view, name="public dataset list view"),
    path("public-model-list-view/", views.public_model_list_view, name="public model list view"),
    path("dataset-list-view-to-fork/", views.model_list_view_to_fork, name="dataset list view to fork"),
    path("public-dataset-data-view:<int:pk>/", views.public_dataset_list_view, name="public-dataset-data-view"),
    path("private-dataset-list-view/", views.private_dataset_list_view, name="private-dataset-list-view"),
    path("private-model-list-view/", views.private_model_list_view, name="private-model-list-view"),
    path("user_dataset_list_path_view/", views.user_dataset_list_path_view, name="user_dataset_list_path_view"),
    path("process-model-options/", views.process_model_options_view, name="process model options"),
    path("human-reinforced-feedback/", views.human_reinforced_feedback_view, name="human reinforced feedback view"),
    path("final-task-analytics/", views.final_task_analytics_view, name="final task analytics"),
    path("previous-tasks/", views.previous_tasks_view, name="previous tasks"),
    path("personal-model-repo/", views.personal_model_repo_view, name="personal model repo"),
    path("personal-dataset-repo/", views.personal_dataset_repo_view, name="personal dataset repo"),
    path("personal-dataset-analysis/", views.personal_dataset_analysis_view, name="personal dataset analysis"),
    path("model-list-choose-one-to-relate-dataset/", views.model_list_choose_one_to_relate_a_dataset,
        name="model_list_choose_one_to_relate_dataset"),
    
    path("login-api/", views.login_api, name="login api"),
    path("models/", api.get_models_api, name="get models api"),    
    path("datasets/", api.get_datasets_api, name="get datasets api"),
    path('models_/', api.ModelList.as_view()),
    path('datasets_/', api.DatasetList.as_view()),
    path('users/', api.UserList.as_view()),
    path('models_/<int:pk>/', api.ModelDetail.as_view()),
    path('users/<int:pk>/', api.UserDetail.as_view()),
    path('datasets_/<int:pk>/', api.DatasetDetail.as_view()),
    path('test_list_random_values/', api.test_list_random_values),
    path('test_get_with_token_authorisation/', api.test_get_with_token_authorisation),
    path('model_form_post/', api.model_form_post),    
]

urlpatterns = format_suffix_patterns(urlpatterns)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models import UniqueConstraint
from django.utils.translation import gettext_lazy as _

# ignore Question and Choice # they are templates to help structure models
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

class Model(models.Model):
    name = models.CharField(max_length=320)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) 
    original_model = models.ForeignKey("self", on_delete=models.SET_NULL, blank=True, null=True) 
    
    model_type = models.CharField(max_length=320)
    model_directory = models.CharField(max_length=2048, unique=True)
    is_public = models.BooleanField(default=False) 

    description = models.CharField(max_length=320, blank=True) 
    
    created = models.DateTimeField(default=timezone.now) 
    updated = models.DateTimeField(auto_now=True) 

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['name', 'user'], name='unique_model_name_user')
        ]
    
class Dataset(models.Model):
    name = models.CharField(max_length=320)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    original_dataset = models.ForeignKey("self", on_delete=models.SET_NULL, blank=True, null=True)
    
    dataset_directory = models.CharField(max_length=2048, unique=True)
    is_public = models.BooleanField(default=False)

    description = models.CharField(max_length=320, blank=True) 
    
    created = models.DateTimeField(default=timezone.now) 
    updated = models.DateTimeField(auto_now=True) 

    class Meta:
        constraints = [
            UniqueConstraint(fields=['name', 'user'], name='unique_dataset_name_user')
        ]

class ModelDataset(models.Model):
    model = models.ForeignKey(Model, on_delete=models.CASCADE) 
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now) 

    class Meta:
        unique_together = ('model', 'dataset',)

class Task(models.Model):
    task_name = models.CharField(max_length=320)

class DatasetActionSet(models.Model):
    class ACTION_SET(models.TextChoices):
        CLEANING = "cleaning", _("CLEANING")
        ANALYSIS = "analysis", _("ANALYSIS")
        ENRICHMENT = "enrichment", _("ENRICHMENT")
        CURATION = "curation", _("CURATION")
        BALANCING = "balancing", _("BALANCING")
        EXPLAINABLE_AI = "explainable_ai", _("EXPLAINABLE_AI")
        UNKNOWN = _("(Unknown)")
        
    action_type = models.CharField(choices=ACTION_SET.choices)

class DatasetAction(models.Model):
    parameters = models.JSONField() 
    action = models.ForeignKey(DatasetActionSet, on_delete=models.CASCADE)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    
    @property
    def action_label(self):
        return self.action.action_type.label
    
class DatasetTaskAction(models.Model):
    """
    one-many task-action.
    A task can have many actions.
    """
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    action = models.ForeignKey(DatasetAction, on_delete=models.CASCADE) 

class ModelActionSet(models.Model):
    class ACTION_SET (models.TextChoices):
        ANALYSIS = "analysis", _("ANALYSIS")
        DISTILLATION = "distillation", _("DISTILLATION")
        FINE_TUNING = "fine_tuning", _("FINE_TUNING")
        EXPLAINABLE_AI = "explainable_ai", _("EXPLAINABLE_AI")
        UNKNOWN = _("(Unknown)")
    
    action_type = models.CharField(choices=ACTION_SET.choices, unique=True)

class ModelAction(models.Model):
    parameters = models.JSONField() 
    action = models.ForeignKey(ModelActionSet, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    
    @property
    def action_label(self):
        return self.action.action_type.label
    
class ModelTaskAction(models.Model):
    """
    one-many task-action.
    A task can have many actions.
    """
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    action = models.ForeignKey(ModelAction, on_delete=models.CASCADE) 

polls/templates/polls/index.html
{% extends base_html %}

{% load custom_filters %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col p-3 mb-1 mx-1 bg-body-tertiary rounded border border-light-subtle">
            <a href="/polls/public-model-list-view/" class="px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">
                <p>List of Top Models</p>
            </a>
            <div class="" style="height: 200px; overflow:scroll;">
                <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
                    {% if model_page_obj %}
                        <ol>
                            {% for model in model_page_obj %}
                                <li style="white-space: nowrap;">
                                    <a class="fw-semibold" temphref="url 'polls:public-model-data-view/?page=' data.id" href="#">{{ model.name }}</a>
                                    <span>
                                        <span class="fw-medium"> {{ model.user }}</span> 
                                        <span class="text-body-secondary text-sm">• {{ model.updated|timesince|upto }} ago</span>
                                    </span>
                                </li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        <p>No model are available.</p>
                    {% endif %}
                    {% if model_private_page_obj %}
                        <ol>
                            {% for model in model_private_page_obj %}
                                <li style="white-space: nowrap;">
                                    <a class="fw-semibold" temphref="url 'polls:public-model-data-view/?page=' data.id" href="#">{{ model.name }}</a>
                                    <span>
                                        <span class="fw-medium"> {{ model.user }}</span> 
                                        <span class="text-body-secondary text-sm">• {{ model.updated|timesince|upto }} ago</span>
                                    </span>
                                </li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if model_page_obj.has_previous %}
                                <a href="?model_page=1&dataset_page={{ dataset_page_obj.number }}" class="btn btn-primary">&laquo; first</a>
                                <a href="?model_page={{ model_page_obj.previous_page_number }}&dataset_page={{ dataset_page_obj.number }}" class="btn btn-primary">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ model_page_obj.number }} of {{ model_page_obj.paginator.num_pages }}.
                            </span>

                            {% if model_page_obj.has_next %}
                                <a href="?model_page={{ model_page_obj.next_page_number }}&dataset_page={{ dataset_page_obj.number }}" class="btn btn-primary">next</a>
                                <a href="?model_page={{ model_page_obj.paginator.num_pages }}&dataset_page={{ dataset_page_obj.number }}" class="btn btn-primary">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </div>
        </div>
        <div class="col p-3 mb-1 mx-1 bg-body-tertiary rounded border border-light-subtle">
            <a href="/polls/public-dataset-list-view/" class="px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">
                <p>List of top datasets</p>
            </a>
            <div class="row bg-body-tertiary" style="height: 200px; overflow:scroll;">
                <div class="" >
                    <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
                        {% if dataset_page_obj %}
                            <ol>
                                {% for dataset in dataset_page_obj %}
                                    <li style="white-space: nowrap;">
                                        <a class="fw-semibold" temphref="url 'polls:public-dataset-data-view/?page=' data.id" href="#">{{ dataset.name }}</a>
                                        <span>
                                            <span class="fw-medium"> {{ dataset.user }}</span> 
                                            <span class="text-body-secondary text-sm">• {{ dataset.updated|timesince|upto }} ago</span>
                                        </span>
                                    </li>
                                {% endfor %}
                            </ol>
                        {% else %}
                            <p>No Dataset are available.</p>
                        {% endif %}
                        {% if dataset_private_page_obj %}
                            <ol>
                                {% for dataset in dataset_private_page_obj %}
                                    <li style="white-space: nowrap;">
                                        <a class="fw-semibold" temphref="url 'polls:public-dataset-data-view/?page=' data.id" href="#">{{ dataset.name }}</a>
                                        <span>
                                            <span class="fw-medium text-primary"> {{ dataset.user }}</span> 
                                            <span class="text-body-secondary text-sm">• {{ dataset.updated|timesince|upto }} ago</span>
                                        </span>
                                    </li>
                                {% endfor %}
                            </ol>
                        {% endif %}
                        <div class="pagination">
                            <span class="step-links">
                                {% if dataset_page_obj.has_previous %}
                                    <input name="dataset_page_num" value="{{ dataset_page_num }}" hidden> 
                                    <input name="model_page_num" value="{{ model_page_num }}" hidden> 
                                    <a href="?model_page={{ model_page_obj.number }}&dataset_page=1" class="btn btn-primary">&laquo; first</a>
                                    <a href="?model_page={{ model_page_obj.number }}&dataset_page={{ dataset_page_obj.previous_page_number }}" class="btn btn-primary">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ dataset_page_obj.number }} of {{ dataset_page_obj.paginator.num_pages }}.
                                </span>

                                {% if dataset_page_obj.has_next %}
                                    <a href="?model_page={{ model_page_obj.number }}&dataset_page={{ dataset_page_obj.next_page_number }}" class="btn btn-primary">next</a>
                                    <a href="?model_page={{ model_page_obj.number }}&dataset_page={{ dataset_page_obj.paginator.num_pages }}" class="btn btn-primary">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                        <br/>
                        <br/>
                        <br/>                        
                    </div>
                </div>
            </div>
        </div>
        <div class="col p-3 mb-1 mx-1 bg-body-tertiary rounded border border-light-subtle">
            <span>List of Top of Verified Energy Efficient Tools</span>
            <ol>
                <li><a href="/polls/" class="px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">
                    tool A
                </a></li>
                <li><a href="/polls/" class="px-0 text-black align-middle link-dark link-underline-dark link-underline-opacity-25 link-underline-opacity-50-hover">
                    tool B
                </a></li>
            </ol>
        </div>
        <div class="col p-3 mb-1 mx-1 bg-body-tertiary rounded border border-light-subtle">
            <div class="row p-3 mb-1 bg-body rounded border border-light-subtle">
                <span>News</span>
            </div>
            <div class="row p-3 mb-1 bg-body rounded border border-light-subtle">
                <span>General Info About The Platform</span>
            </div>
        </div>
    </div>
</div>


{% endblock %}

polls/templates/polls/model_list_choose_one_to_fork.html
{% extends "base_logged_in.html" %}

{% load custom_filters %}
{% block content %}

<div class="container">

<h1>Fork a Model</h1>

<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    
    {% if public_model_list %}
    <fieldset class="mt-3">
        <legend class="fs-6 fw-medium" hidden></legend>
        {% for model in public_model_list %}
        <div class="form-check bg-body-tertiary rounded border border-light-subtle shadow-sm ">
            <label class="form-check-label p-1" for="id_model_{{ model.id }}">
                <input class="form-check-input" type="radio" name="model_id" value="{{ model.id }}" id="id_model_{{ model.id }}" required>
                <a class="text-smd text-start" temphref="url 'polls:private-model-data-view/?page=' data.id" href="#" role="button">
                    <span class="text-sm">{{ model.name }}</span> 
                </a>
                <div>
                    <span class="text-body-secondary text-sm">{{ model.user }}</span> 
                    <span class="text-body-secondary text-sm">• {{ model.updated|timesince|upto }} ago</span>                    
                </div>
            </label>
        </div>
        {% endfor %}
    </fieldset>
    {% else %}
        <p>No models are available.</p>
    {% endif %}

    <div class="form-floating mb-1 mt-3">
        <input type="text" name="name" id="id_name" class="form-control" placeholder="" required>
        <label for="id_name">* Name</label>
    </div>

    <div class="form-floating mb-1">
        <input type="text" name="model_type" class="form-control" id="floatingModeltype" placeholder="TypeOneNet" maxlength="320" required>
        <label for="floatingModeltype">* Model Type</label>
    </div>

    <div class="form-floating mb-1">
        <input type="text" name="description" id="id_description" class="form-control" placeholder="">
        <label for="id_description">description</label>
    </div>

    <fieldset class="mb-1">
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_0">
                <input class="form-check-input" type="radio" name="is_public" value="1" id="id_is_public_0" required checked>
                private
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_1">
                <input class="form-check-input" type="radio" name="is_public" value="2" id="id_is_public_1" required>
                public
            </label>
        </div>
    </fieldset>
    
    <button type="submit" class="btn btn-primary">Fork</button>
</form>

</div>

{% endblock %}

polls/templates/polls/profile.html
{% extends "base_logged_in.html" %}

{% load static %}

<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


<div class="container">
    <div class="row">
        <div class="col p-3 mb-5 bg-body-tertiary rounded border border-light-subtle">
            Personal Info
            <div>{{ username }}</div>
            <div>{{ email }}</div>
        </div>
        <div class="col p-3 mb-5 bg-body-tertiary rounded border border-light-subtle">
            Personal Analytics
        </div>
        <div class="col p-3 mb-5 bg-body-tertiary rounded border border-light-subtle">
            <div class="row p-3 mb-5 bg-body rounded border border-light-subtle">
                Profile Views
            </div>
            <div class="row p-3 mb-5 bg-body rounded border border-light-subtle">
                Overall Green Index
            </div>
        </div>
    </div>
</div>

    
{% endblock content %}
    

polls/templates/polls/upload_file.html
{% extends "base_logged_in.html" %}

{% block content %}


<div class="container">

<h1>Upload a Folder</h1>

<form method="post" enctype="multipart/form-data" action="" >
    {% csrf_token %}

    <div class="form-floating mb-1">
        <input type="text" name="title" id="id_title" class="form-control" required>
        <label for="id_title">Title</label>
    </div>

    <label for="id_folder" class="form-label">Folder:</label>
    <input type="file" name="file" id="id_folder" class="form-control mb-1" webkitdirectory mozdirectory directory multiple required>
    <input type="text" id="directories" name="directories" hidden/>

    <label for="id_zip_file" class="form-label">Zip File:</label>
    <input type="file" accept=".zip,.rar,.7zip" name="zip_file" id="id_zip_file" class="form-control mb-1">
    <input type="text" id="directories" name="directories" hidden/>
    
    <div class="form-floating">
        <input type="text" name="name" id="id_name" class="form-control mb-1">
        <label for="id_name">Name</label>
    </div>
    
    <div class="input-group mb-3">
        {{ form.filepaths.errors }}
        <label for="id_filepaths" class="input-group-text">File Paths</label>
        <select type="text" name="filepaths" id="id_filepaths" class="form-select">
            {% for field in form.filepaths %}
                <option value=''>{{ field }}</option>
            {% endfor %}
        </select>
    </div>
    
    <fieldset>
        <legend class="fs-6 fw-medium">Publicity</legend>
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_0">
                <input class="form-check-input" type="radio" name="is_public" value="1" id="id_is_public_0" required checked>
                private
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label" for="id_is_public_1">
                <input class="form-check-input" type="radio" name="is_public" value="2" id="id_is_public_1" required>
                public
            </label>
        </div>
    </fieldset>
    <br>
    
    {% for field in form %}
        <div class="fieldWrapper ">
            {{ field.errors }}
            <label for='{{ field.label_tag }}' >
                {{ field.label_tag }}
            </label>
            <div class="" id='{{ field.label_tag }}'>
                {{ field }}
            </div>
        </div>
    {% endfor %}

    <button type="submit">Upload</button>
</form>

</div>

<script>
    files = document.querySelector("#id_folder").files;
    document.querySelector("#id_folder").addEventListener("change", function() {
        files = document.querySelector("#id_folder").files;
        var directories = {}
        for (var file of files) {
            file.webkitRelativePath
            directories[file.name] = file.webkitRelativePath
        }
        directories = JSON.stringify(directories);
        document.querySelector("#directories").value = directories
    });
</script>

{% endblock %}